export interface IParam {
  seqNo?: number | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  state?: string | null;
  city?: string | null;
  zipCode?: string | null;
  currResidenceSince?: string | null;
  residenceType?: string | null;
  employmentType?: number | null;
  organizationType?: string | null;
  employerName?: string | null;
  workExpInCurrentOrg?: string | null;
  totalWorkExp?: string | null;
  netMonthlySalary?: string | null;
  salaryCreditBank?: string | null;
  businessType?: string | null;
  businessName?: string | null;
  totalBussTenure?: string | null;
  itrCount?: string | null;
  grossAnnualTurnover?: string | null;
  grossAnnualProfit?: number | null;
  requiredPLAmount?: string | null;
  hasObligations?: string | null;
  createdOn?: string | null;
  createdBy?: string | null;
  updatedOn?: string | null;
  updatedBy?: string | null;
  leadQueueCode?: string | null;
  emiEligibility?: string | null;
  customerID?: string | null;
  applicationID?: string | null;
  matchedBank?: string | null;
  errorCode?: string | null;
  errorComments?: string | null;
  panCardUploaded?: string | null;
  addressProofUploaded?: string | null;
  addressProofType?: string | null;
  salariedPaySlipsUploaded?: string | null;
  salariedBankStatementsUploaded?: string | null;
  itrFileUploaded?: string | null;
  businessRegistrationUploaded?: string | null;
  businessPremises?: string | null;
  gstRegistered?: string | null;
  businessRegProof?: string | null;
  yrsAtCurrentCity?: string | null;
  otherIncome?: string | null;
  salaryType?: number | null;
  isSubmitted?: number | null;
  migratedtoCRM?: number | null;
  netAnnualProfit?: string | null;
  residenceOwned?: number | null;
  preferredContactMode?: string | null;
  scheduledDateTime?: string | null;
  lastUserPosition?: string | null;
  submittedOn?: string | null;
  salaryCreditedBankType?: string | null;
  employerType?: string | null;
  callBackDateTime?: string | null;
  canCallAnyTime?: number | null;
  isCallRightNow?: number | null;
  crmProgressRank?: number | null;
  crmProgressStatus?: string | null;
  recordToSync?: number | null;
  isEligible?: string | null;
  lastPosition?: string | null;
  mobileNumber?: string | null;
  creditScore?: number | null;
  errCreditReportCount?: number | null;
  dateofBirth?: string | null;
  panNumber?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  middleName?: string | null;
  pincode?: string | null;
  dateOfLatestCreditScore?: string | null;
  dateOfFirstCreditScore?: string | null;
  leadCategory?: string | null;
  addressInformation?: Array<{
    seqNo: number | null;
    addressLine1: string | null;
    addressLine2: string | null;
    city: string | null;
    state: string | null;
    zipCode: string | null;
    isActive: number | null;
    addressType: string | null;
    source: string | null;
  }>;
  emailAddresses?: Array<{
    seqNo: number | null;
    emailAddress: string | null;
    isActive: number | null;
    emailType: string | null;
  }>;
  businessRegistrationNames?: Array<string>;
  isNewApplication?: boolean;
  businessRegistrationType?: string | null;
  fastTrackPoint?: boolean;
  nonPreferredSalaryCreditedBank?: string | null;
  repayableYears?: string | null;
  educationalQualification?: string | null;
  hdfcSavingsAccount?: string | null;
  noOfDependants?: string | null;
  yrsAtCurrentResidence?: string | null;
}

export interface IResponse {
  error: boolean;
  status: number;
  message: string;
  data: object;
}
