export interface IParam {
  customerID: number;
  campaignCode: string;
}

export interface IPLAppData {
  error: boolean;
  status: number;
  message: string;
  data: {
    list: {
      appID: number;
      isNewApp: boolean;
      isApplicationFinished: boolean;
      applicationDetails: {
        seqNo: number;
        addressLine1: string | null;
        addressLine2: string | null;
        state: string | null;
        city: string | null;
        zipCode: string | null;
        currResidenceSince: string | null;
        residenceType: string | null;
        employmentType: number | null;
        organizationType: string | null;
        employerName: string | null;
        workExpInCurrentOrg: string | null;
        totalWorkExp: string | null;
        netMonthlySalary: string | null;
        salaryCreditBank: string | null;
        businessType: string | null;
        businessName: string | null;
        totalBussTenure: string | null;
        itrCount: string | null;
        grossAnnualTurnover: string | null;
        grossAnnualProfit: number | null;
        requiredPLAmount: string | null;
        hasObligations: string | null;
        createdOn: string | null;
        createdBy: string;
        updatedOn: string | null;
        updatedBy: string;
        leadQueueCode: string | null;
        emiEligibility: string | null;
        customerID: string;
        applicationID: string;
        matchedBank: string | null;
        errorCode: string | null;
        errorComments: string | null;
        panCardUploaded: string | null;
        addressProofUploaded: string | null;
        addressProofType: string | null;
        salariedPaySlipsUploaded: string | null;
        salariedBankStatementsUploaded: string | null;
        itrFileUploaded: string | null;
        businessRegistrationUploaded: string | null;
        businessPremises: string | null;
        gstRegistered: string | null;
        businessRegProof: string | null;
        yrsAtCurrentCity: string | null;
        otherIncome: string | null;
        salaryType: number | null;
        isSubmitted: number | null;
        migratedtoCRM: number | null;
        netAnnualProfit: string | null;
        residenceOwned: number | null;
        preferredContactMode: string | null;
        scheduledDateTime: string | null;
        lastUserPosition: string | null;
        submittedOn: string | null;
        salaryCreditedBankType: string | null;
        employerType: string | null;
        callBackDateTime: string | null;
        canCallAnyTime: number;
        isCallRightNow: number;
        crmProgressRank: number;
        crmProgressStatus: string;
        recordToSync: number;
        isEligible: string;
        lastPosition: string | null;
        mobileNumber: string | null;
        creditScore: number;
        errCreditReportCount: number | null;
        dateofBirth: string | null;
        panNumber: string | null;
        firstName: string | null;
        lastName: string | null;
        middleName: string | null;
        pincode: string | null;
        dateOfLatestCreditScore: string | null;
        dateOfFirstCreditScore: string | null;
        leadCategory: string | null;
        hdfcSavingsAccount: string | null;
        repayableYears: string | null;
        yrsAtCurrentResidence: string | null;
        noOfDependants: string | null;
        educationalQualification: string | null;
      };
      businessRegistrationDetails: Array<any>;
      addressInformationDetails: Array<{
        addressLine1: string | null;
        addressLine2: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        addressType: string | null;
        seqNo: number;
        isActive: number;
        source: string | null;
      }>;
      emailInformationDetails: Array<{
        emailAddress: string | null;
        emailType: 'OFFICE' | 'PERSONAL';
        source: string | null;
        seqNo: number;
        isActive: number;
      }>;
    };
  };
}
